/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface.h"

bool_t
xdr_resource (XDR *xdrs, resource *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->res_type, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->perms, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user (XDR *xdrs, user *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->req_auth_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resources_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->reg_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->val_time))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->automatic_refresh))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->res, sizeof (resource), (xdrproc_t) xdr_resource))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_token_pair (XDR *xdrs, token_pair *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->resources_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->reg_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->val_time))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_status (XDR *xdrs, status *objp)
{
	register int32_t *buf;

	 if (!xdr_token_pair (xdrs, &objp->pair))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->stat, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_1_argument (XDR *xdrs, request_access_token_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_delegated_action_1_argument (XDR *xdrs, validate_delegated_action_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg3, ~0))
		 return FALSE;
	return TRUE;
}
